branches:
    only:
        - v2

language: node_js
node_js:
    - lts/*
cache:
    directories:
        - node_modules

install:
    - npm install
    - npm run build
deploy:
    provider: pages
    on:
        branch: v2
    skip_cleanup: true
    local_dir: dist/
    github_token: $TOKEN
